// <auto-generated />
using Commissionor.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Commissionor.WebApi.Migrations
{
    [DbContext(typeof(CommissionorDbContext))]
    [Migration("20180212150834_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Commissionor.WebApi.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Door")
                        .IsRequired();

                    b.Property<string>("ReaderId")
                        .IsRequired();

                    b.Property<string>("Room")
                        .IsRequired();

                    b.Property<string>("Site")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ReaderId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Commissionor.WebApi.Models.Reader", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Placement")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Commissionor.WebApi.Models.Location", b =>
                {
                    b.HasOne("Commissionor.WebApi.Models.Reader")
                        .WithMany("Locations")
                        .HasForeignKey("ReaderId")
                        .HasConstraintName("FK_Location_Reader")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
